### PR TITLE
adding python 2 check

### PR DESCRIPTION
**Pull request by aalquist**
confirm the CLI tool has picked the correct python runtime (version 3) before proceeding

### CODE REVIEW

**Comment by vreddhi** [comment]
@aalquist Thanks for this commit. Is this tested on a machine or `pyenv` where python2 is installed?

**Comment by aalquist** [comment]
I tested on my machine with python 3 for positive test case. I only tested the main file on a python 2 machine. Can you help me confirm?

**Comment by rajiv** [comment]
the `create-dns` functionality should be split out into a separate PR from checking for python 2.

**Comment by aetsai** [comment]
python2 eol 2020

**Pull request closed without merging**
